### ISSUE TITLE
Increase trace/sql test coverage

### ISSUE THREAD

**Issue by ardaguclu** [beatlabs/patron#133]
## Is your feature request related to a problem? Please describe

trace/sql package's test coverage is 6% and pulls down average coverage to 77%. By mocking trace and other external libraries and implementing unit tests, test coverage can be increased.

**Comment by ardaguclu** [comment]
I can work on that issue @mantzas

**Comment by mantzas** [comment]
@ardaguclu For these tests we need to introduce integration tests. The examples folder already contains a valid docker-compose for this. What's needs to be done:
- For local development we can use the docker-compose to start all required services (postgres)
- For ci tests we have to start postgres as part of circleci in order to run also theses tests
- Make ci command needs to include integration build tags
This will be a rather big task if you are up to it...

**Comment by ardaguclu** [comment]
I would like to spend some time introducing integration tests, applying the steps you listed above. But of course it is going to take time.

**Comment by mantzas** [comment]
@ardaguclu no worries...

**Comment by ardaguclu** [comment]
>     * For local development we can use the docker-compose to start all required services (postgres)
Examples directory is not only for showing sample use cases but also used for integration tests, hence sixth example is needed which uses postgres(already embbeded into `docker-compose`).
> 
>     * For ci tests we have to start postgres as part of circleci in order to run also theses tests
For ci tests, I could not find any integration triggers when circleci executes. In terms of integration tests, this one will be the first.

Are these comments correct?, and after the integrations are completed for trace/sql, next step I guess is to write unit tests.

**Comment by mantzas** [comment]
@ardaguclu There is already a sixth example in PR about gRPC. We have not used examples to show of the "clients" in the trace package so it is not necessary to have an example for that. Just plain integration tests suffice e.g. `publisher_integration_test.go`.
Since our integration test is done via build flags `// +build integration` we need only to add the build flag to the ci. we need to add only `-tags=integration` to the coverci target of the makefile.
