### ISSUE TITLE
Async Component Readiness

### ISSUE THREAD

**Issue by lvrach** [beatlabs/patron#19]
## The problem

Our service has a health endpoint for deploying our service in staging and production environments. It also relies upon Kafka for receiving critical data for its operation. Thus the connection with Kafka nodes determines our service readiness. 

So far our readiness detection relied upon receiving the first message from a Kafka topic:
```
func (kc *kafkaComponent) Process(msg async.Message) error {
        .....

	if !kc.gotMessage {
		kc.ch <- true
		kc.gotMessage = true
	}
```

note: `kc.ch` notifies our health component

However, in environments with low traffic or zero traffic, that strategy caused problems with our existing deployment tools.

In order for our service to respond correctly to readiness requests, we need a mechanism that notifies heath component when we are successfully connected to kafka, not when we receive the first message.

Unfortunately I could not find a workaround without requiring additions in the patron framework. 
Due to blocking nature of run and the retry strategy mechanism introduced in async component, there is no way to determine if the async component is successfully content and ready to consume.

## Solution
I think the simplest solution would be to introduce a readiness handler option for the async component:

```
cmp, err := async.New(
    "kafka-topic", 
    kafkaCmp.Process, 
    cf, 
    async.ConsumerRetry(retries, retryTimeout)
    async.ReadinessHandler(func() {
        kc.ch <- true
    })
)
```

Apart for service readiness this handler could be useful in other cases such as debugging and logging.

**Comment by mantzas** [comment]
The way patron async component handles connection failures is by returning a error when the consumer return a error.
We have implemented a configurable retry with a time backoff for handling transient failures.
Eventually the async component will return a error and causes the service to fail and exit the application.

The proposed solution only gives a hint that the connection succeeded at some point but after that it does not give any clue about the state of the async component.
What should the "readiness" do when we have transient failures?

Beware that the async component is agnostic of the consumer used (Kafka, AMQP, SQS etc.), so in the case of a AWS SQS consumer, which is HTTP based, this could not be determined easily.

Since you are basing the readiness on the first message received maybe you should consider changing this in order to cover high traffic and low traffic scenarios and relax the "readiness" for low traffic scenarios?

**Comment by mantzas** [comment]
We should investigate the implementation of readiness and liveness of a all component and the integration in the health check exposed through HTTP.
Issue #24 will try to find a generic solution for this. 

@lvrach you could, as a workaround, clone the existing kafka consumer and add any code you like to fit your need until a generic solution will be created.
