### ISSUE TITLE
CI reports an error on test suite

### ISSUE THREAD

**Issue by mantzas** [beatlabs/patron#243]
## Is your feature request related to a problem? Please describe

There is an error on the CI tests. https://github.com/beatlabs/patron/actions/runs/185826310
Locally everything works fine.

## Is this a bug? Please provide steps to reproduce, a failing test etc.

Yes

**Comment by mantzas** [comment]
@drakos74 can you take a look, it seems that it is in one of the tests on HTTP caching.

**Comment by tpaschalis** [comment]
The test in question calls `runRoute` which contains
```go
	go func() {
		err = cmp.Run(ctx)
		assert.NoError(t, err)
	}()
```

The error is produced by [this](https://github.com/golang/go/blob/b4ea67200977b99ede1885ed77e034a2fdf434f5/src/testing/testing.go#L690) line; I think the issue here is that in that goroutine, the error is returned after the parent test exits.

I'm not 100% sure, but I think we could defer the assertion at the end of runRoute instead.

**Comment by mantzas** [comment]
@tpaschalis or setup a signal channel in order to block and wait for things to clear!!!
