### ISSUE TITLE
Async Retry Strategy Improvements

### ISSUE THREAD

**Issue by sgarcez** [beatlabs/patron#266]
## Is your feature request related to a problem? Please describe

The current retry strategy employed in the [async component](https://github.com/beatlabs/patron/blob/master/component/async/component.go#L133) is a common pattern used for single tasks ([example](https://docs.microsoft.com/en-us/azure/architecture/patterns/retry#example)) but the async component is a long running process which means that we can end up in situations like the following:

- The number of retries is set to 10
- We observe 1 process error per day
- On day 11 the component exits (and so does the application, leading to a restart of the service)

## Describe the solution

There are many possible solutions, here are some simple options, in order of complexity:

1. Only consider sequential errors (any successfully processed message resets the retry counter): 
    - If we only receive errors x times in a row, we exit the component.
2. Same as above but time bound instead of count bound:
    - If we only receive errors for 10s, we exit.
3. Time bound non sequential:
    - If we receive more than x errors in x time we exit the component.

Better yet would be to abstract this in a way that could be used also for the upcoming Kafka component?

**Comment by mantzas** [comment]
Yes this seems to be an issue i agree. 
Kafka is a different beast that AMQP or SNS/SQS.
The reason is that Kafka is a stream and you cannot/should not stop the stream if you get bad data whereas SQS has the notion of a DLQ. Also in SQS you can ACK messages individually but in Kafka if you ACK a message you ACK also the ones with a smaller index...
Any time based solution has the problem that we do not know how slow they  are in order to set the reset based on time.
Suggestion.: Would it make sense to reset whenever a retry succeeds?

**Comment by sgarcez** [comment]
Yes a reset was my first option above, it's the simplest one for sure!

**Comment by sgarcez** [comment]
To be reviewed once the new standalone async components are in place.

**Comment by mantzas** [comment]
@sgarcez Hey, this is handled in v2 so we close this one.
