### ISSUE TITLE
Uncompressed paths property is not set in HTTP component builder

### ISSUE THREAD

**Issue by azarakovskiy** [beatlabs/patron#303]
## Is your feature request related to a problem? Please describe

By default, everything is now compressed if possible. Even the uncompressed paths.

## Is this a bug? Please provide steps to reproduce, a failing test etc.

Yes. Request a `/metric` endpoint with `Accept-Encoding: gzip`.

## Describe the solution

The default value from a default builder is never set. This is the fix:
https://github.com/taxibeat/authentication-service/pull/75/commits/3977d25d2e2bbb0d4c320350cb716e4319591e9f

**Comment by tpaschalis** [comment]
I'm opening a PR for a fix to this issue as we speak; it allows setting 'uncompressed' paths in the builder, in addition to the three default ones.

Specifically for /metric, as you'll see by defining a "Accept-Encoding: deflate" header, the route is correctly skipped from our middleware. 

On the other hand, if you set "Accept-Encoding: gzip", the response will still be compressed; this is not from our side, but (I suppose) due to `promhttp`'s handler.
