### ISSUE TITLE
Provide default logging

### ISSUE THREAD

**Issue by tsauvajon** [beatlabs/patron#373]
## Problem

As pointed out in the documentation:
> If the setup is omitted the package will not setup any logging!

The design of the Patron logger is confusing for new users. In one of our services, we did the following:

```go
import "github.com/beatlabs/patron/log"

func main() {
    err := doSomeSetup()
    if err != nil {
       log.Errorf("setup: %w", err)
    }

    patron.New()
}
```
When the setup part failed, we had no logs whatsoever.

The patron/log package provides static functions to log, but they're actually not working by default, you need to create a new Patron client that will, with side effects, update the static functions in the `log` package to log to Stderr.

Also, manually initialising the logger (with `log.Setup(log.Logger)`) has 3 problems:
- it is not obvious we need to do it: the design doesn't make it clear, and no error/panic happening when we try to log with a un-initialised logger.
- it is not well documented: the `log` documentation only says we can do `log.Setup(log.Logger)`, but doesn't show us how. We have to dig into the code to understand how we're supposed to do it
- it gets overwritten as soon as we initialise a Patron client

## Solution

We can make the design more straight-forward by applying the following:

1. Make the static log functions initialised by default. We currently do that anyway in patron.New(), why does it have to wait?
2. Stop `patron.New()` from having side effects on static log methods (1. it discards any previous `log.Setup()`, 2. it acts like magic: patron.New() modifies static functions from another package)
3. In the documentation front-page (README.md), provide a working example on how to set-up a Patron Client.

## Additional context

Almost every logger in Golang and other languages work in one of two ways:
- provide a logger object that you can use to log (that is never `nil`)
- provide static functions that work by default and that you can customise

In our case, we provide both approaches but go against the common practice of only being able to use initialised logs.

Here's what some Golang logging packages do:
[Zap](https://github.com/uber-go/zap) and [Google logger](https://github.com/google/logger) provide no static functions; you can't log with non-initialised loggers, you have to create a new logger to log anything.

-> In our case, we provide both, but if we do `log.FromContext(ctx)` and the logger isn't initialised, we're back to square 1 and have a logger that doesn't log.

[Zerolog](https://github.com/rs/zerolog) and [Logrus](https://github.com/sirupsen/logrus) provide static functions that match with the standard library `log`, so you can replace them, in place. The main differences with Patron are:
- the logger is initialised by default; if you remplace the std logger import directive with zerolog/logrus, it just works
- you have direct control over the singleton: you can update them (log level, formatter etc.) with static methods. With Patron, you have no direct-and-easy control over the Singleton to just change one setting.

**Comment by mantzas** [comment]
@tsauvajon `patron.New()` does a lot of things under the hood for the observability part. Check out line: https://github.com/beatlabs/patron/blob/8831b23b95dc1201b590238f9b5ab1040cab29f7/service.go#L226
check out also this function `err := setupObservability(name, version, cfg.fields, cfg.logger)` in there to understand much better what happens.
With that in mind how could we statically setup tracing and logging when we have to pass in some argument like name and version?

**Comment by tsauvajon** [comment]
I realise that we won't necessarily have the same logger before and after `patron.New()`. I still think it is a good idea.

1. That's already what we do!

Currently, we DO have a different logger before and after `patron.New()`. Before, it's a "sink" (`nilLogger`), and after, it's zerolog by default or whatever you want to pass as a logger.

2. Default values should be the same for before `patron.New()` and after `patron.New()`.

That way, if you just want to get started with Patron and do something simple, you won't have any weird behaviour (not having any logs until you setup patron OR have different loggers before/after setting up patron).

3. If you want to override the defaults then it's up to you to be clever about it

I don't think many users override the default logger. For the minority of users that do, they should start reading a bit more documentation and understand what needs to happen. For that, we should probably make the documentation a bit more explicit and explain that to change a logger, you should do something like that:

```go
import "patron/log"

func main() {
    myNiceLogger := myCustomNewLogger
    log.Setup(myNiceLogger)

    [... some code that can print stuff ...]
    
    patron.New(...).WithLogger(myNiceLogger)
}
```

For this specific case (overriding the defaults), the behaviour is exactly what we currently have.

**Comment by mantzas** [comment]
We never had an issue in our services because the first thing that we do is setting up patron with `patron.New()`.
The above code has a problem because log.Setup return an error which you have to log and handle.
The only thing we could do is the enable by default the zerolog implementation but that would create the mentioned inconsistency.
TBH I cannot see a clear solution and benefits in any case expect that we introduce a possible inconsistency by setting up zerolog as the default.
Also keep in mind that if you follow the examples and do as the first thing in your main the `patron.New()` after that logging works exactly as it should with all the custom fields.

**Comment by jakubzapletal** [comment]
Unfortunately, I have a different experience with Patron. 
First, when I am looking at `patron.New` I see
```go
// New creates a builder with functional options.
func New(name, version string, options ...Option) (*Builder, error) {
```
which tells me it creates a builder and I would not assume it is required to be the first thing to set up before anything else because of logging.
I guess there is an assumption all developers know Patron from the ground up but when I am looking at Go services in our team it was not clear for them. Before there is something related to Patron there are many `fmt` outputs which would lead to a different formatting than the rest of the logs or using `patron/log` that outputs nothing.
I can also see some services are using the older version of the Patron where there were functions `patron.SetupLogging()` and `patron.SetupLoggingWithFields()`. That is quite transparent to me to be used before I want to use any Patron logging.
To give you some context, Thomas came with this issue as a result of what we were challenged yesterday when we were trying to deploy a service but the service was exiting without any message telling us what is going on. The service was using `patron/log` to output initial errors.

**Comment by mantzas** [comment]
@jakubzapletal If you follow the example you should not have this problem at all. We actually improved the usage of patron because in the beginning we had `patron.SetupLogging()` and then the patron.New so we condensed the two steps into one making it a one step approach which is much more user friendly.
The previous approach did though have the same issue because setting up logging and tracing might return an error which you have to handle (usually log and exit(1)).
As you can see there is no perfect solution and given that the current proposal would introduce an inconsistency in the logging the current one is the lesser of two evils.
Would it make sense to make a quick call to showcase this?

**Comment by tsauvajon** [comment]
Where is that example?

I can only see consumer examples: https://github.com/beatlabs/patron/tree/master/examples

**Comment by mantzas** [comment]
@tsauvajon take a look at https://github.com/beatlabs/patron/blob/3cabbf34ce4970a31150062227a33fe62ec03c51/examples/kafka/main.go#L51
On line 51 we setup patron with a textlogger, so not the default one and the only case that something did go wrong is if this call fails (which should almost never happen).
So in line 53 we are handling the logging and then exit.
After line 55 the only logger that should be used and fully set up is the patron one.
