### ISSUE TITLE
Migration to AWS SDK V2

### ISSUE THREAD

**Issue by tsauvajon** [beatlabs/patron#430]
AWS released the V2 of their SDK. I just learned about it recently.

https://aws.amazon.com/blogs/developer/aws-sdk-for-go-version-2-general-availability/

They claim that it `offers significant performance improvements in CPU and memory utilization over version 1`.

Quite importantly, from a quick glance and a look at some problems we had, it looks like developer experience is much better than V1:
- sensible defaults for many things
- the API looks simpler and easier to use

Is this worth looking into, or is it something we don't want to do?

**Comment by mantzas** [comment]
Yes, It makes a lot of sense but we need to find a way to move forward.
Maybe we should introduce a v2 version of the clients and components and mark the old ones as deprecated.
This is how we dealt with Kafka v1 and v2.

**Comment by tsauvajon** [comment]
> Yes, It makes a lot of sense but we need to find a way to move forward.
> Maybe we should introduce a v2 version of the clients and components and mark the old ones as deprecated.
> This is how we dealt with Kafka v1 and v2.

That sounds reasonable, it would allow non-breaking changes, and making step-by-step upgrades (one component at a time, instead of everything at once).

**Comment by gmaz42** [comment]
Today I was looking at this issue in order to pick it up; these are the Go packages in Patron that use AWS SDK:
* `component/async/sqs` (deprecated)
* `client/sns` (deprecated) and `client/sns/v2`
* `client/sqs` (deprecated) and `client/sqs/v2`
* `component/sqs`
* `component/sns`

While it is possible to introduce a `/v2` for the components, we already used that for the clients? Having `v2` mean two different things (for component or client) would not be a good thing?

Suggestions are welcome :relaxed: will not proceed until we decide about the optimal directory structure.

**Comment by mantzas** [comment]
We could have the following 2 options:
1. introduce a v3
2. make a breaking change and replace all of them with the new library
Other options are highly welcome but eventually we have to deprecate some code.

**Comment by tsauvajon** [comment]
From the user standpoint, I'm in favour of a breaking change and depreciation (-> old code gets deleted when v1.0 gets released) of the old API, with a clear path for migration to Patron v1.0 (maybe a small guide?). That's a bit of work that needs to be done by the users, but it is much clearer for everyone and avoids confusion. I can cite a single exemple where we were stuck with a Patron bug for ~1.5 years, just to figure out in the end that we were unknowingly using a deprecated package.

How feasible and how good of an investment would it be to write a script that automates the upgrade? I'm thinking of how Rust does it, of course they have way more users so the investment makes sense for them: https://doc.rust-lang.org/edition-guide/editions/transitioning-an-existing-project-to-a-new-edition.html

**Comment by mantzas** [comment]
BTW Go had this feature `go fix` before Rust which eventually copied it and others like rustfmt. https://pkg.go.dev/cmd/fix.

**Comment by tsauvajon** [comment]
Oh, I didn't know about this! It would make sense to dig into it; if it makes migrations more easy, it would be very helpful to drive Patron v1.0 adoption.

**Comment by gmaz42** [comment]
> Oh, I didn't know about this! It would make sense to dig into it; if it makes migrations more easy, it would be very helpful to drive Patron v1.0 adoption.

I think these automatic fix tools only show their worth in quantity: when you have a lot of trivial changes, think about upgrading kubernetes plugins codebases for example.

Our case is different though: we have a few and perhaps not trivial e.g. requiring developer's thinking to make a choice.

If we go for breaking changes then better to do it all at once so that users will migrate directly to the latest one; shall I create a PR to do this?
