### ISSUE TITLE
Migrate to functional options and replace any builder patterns

### ISSUE THREAD

**Issue by mantzas** [beatlabs/patron#462]
## Is your feature request related to a problem? Please describe

We are using in some cases the builder pattern and in other the functional option pattern.
We should migrate all code to the functional option pattern.
The upside is that the code will become much simpler since we do not need to have two separate struct to support this (builder and the thing you build).
This is a BREAKING CHANGE and we should do it before we move to v1.0 release. 

## Describe the solution

Replace only the non deprecated builder patterns.

## Things to tackle

- [ ] Client: Kafka v2 (v1 will be deprecated)
- [ ] Component: gRPC
- [ ] Service, main

**Comment by wishperera** [comment]
Hola Team 👋 
Is anyone working on this task atm? If not I would like to contribute to this  :raised_hands:

**Comment by mantzas** [comment]
@wishperera go fot it!

**Comment by wishperera** [comment]
Hello Team,
Following up on this, I noticed that the `client/kafka/v2`  follows `factory` pattern and has only mandatory input parameters  
1. kafka broker list
2. sarama config
and no optional parameters. Given this should we consider moving this to `functional options` pattern since the options will be pretty much never used?

**Comment by mantzas** [comment]
@wishperera Hey, I agree that it does not make much sense in this case.
