### ISSUE TITLE
Status Code and Request Counters Issue (Metrics)

### ISSUE THREAD

**Issue by gkech** [beatlabs/patron#64]
## Is your feature request related to a problem? Please describe

While working on the examples that Patron provides (refer to this: `https://github.com/beatlabs/patron/tree/master/examples/first`) I observed that the metrics have an issue. More specifically, code status counters and request counters do not increase as they should be. The issue was observed in v0.23 and v0.24 of Patron. 

## Is this a bug? Please provide steps to reproduce, a failing test etc.

When I hit the `POST` `localhost:50000/`, I receive a `500 Internal Server Error`. The counter for `sync_requests{endpoint="POST-/",error="false"}` is increased by one (here we expected an increase to `error="true"`). Furthermore,  we do not have an increase of the `sync_http_requests{endpoint="POST-/",status_code="5xx"}` counter. I observed the results through `localhost:50000/metrics`.

**Comment by mantzas** [comment]
There are 2 problems here.

- v0.22.0, which refactored middlewares, did break the metrics of type `sync_http_requests{endpoint="POST-/",status_code="5xx"} 0`
- the `sync_requests{endpoint="POST-/",error="false"}` error tag seems not to work even before v0.21.0

We will take a look at the middlewares again in order to determine what broke.
We will also see why the error tag is not working.
Nice catch @gkech
