### ISSUE TITLE
Support Kafka consumer group with multiple topics

### ISSUE THREAD

**Issue by mantzas** [beatlabs/patron#71]
## Is your feature request related to a problem? Please describe

After splitting the consumer group types in different packages #70 we can now support consumer groups on multiple topics.

**Comment by moukoublen** [comment]
I'd like to pick this :point_up: up.

I was thinking about adding somehow the ability to get the topic (that a message was arrived to) from the `async.Message` interface.

I think it would be useful to have this information in the processing side of code considering that we could have messages from different topics (that need different object decoding, different kind of processing e.t.c.) all arriving in a single processing function. 

But since the  `async.Message` interface hides some different kind of messages we will need an abstract way to do that.

A possible implementation could be to add a metadata function in `async.Message` interface.

```golang
type Message interface {
	Context() context.Context
	Decode(v interface{}) error
	Ack() error
	Nack() error
	Metadata(key string) string //or interface {}
}
```
and have something like this in private `kafka.message` 

```golang
const MetadataKeyTopic = "kafkaTopic"

//...

func (m *message) Metadata(key string) string {
	switch key {
	case MetadataKeyTopic:
		return m.msg.Topic
	default:
		return ""
	}
}
```

And return empty string (or `struct{}` if we choose the `interface{}` return type) in other message implementations for now.

What do you think?

**Comment by mantzas** [comment]
@moukoublen actually the change here requested is fairly simple. we are passing only on topic to sarama but sarama handles a list of topics...
Could we introduce a `Source() string` instead of metadata for this purpose? 
I believe AMQP (queue), SQS (queue) and Kafka (topic) have the noting of the source...
Metadata is too generic and needs probably accompanying keys in order to get the desired value.

**Comment by moukoublen** [comment]
Yes the main change is to use array of topics in group consumer construction and pass them to sarama consumer.

I was talking about the "other" side also. Yes a single `Source() string` function sounds very good. 

I will proceed with that :relaxed:

**Comment by mantzas** [comment]
@moukoublen could you also as part of this ticket make the changes also to AMQP, and SQS in order to have feature parity? We could also split the ticket in 2 and make first the Source implementation and then the multiple topic implementation... It is up to you...

**Comment by moukoublen** [comment]
Yes I could introduce those changes too. No need to split the ticket.
